### ISSUE TITLE
com.poovam.pinedittextfield.LinePinField not visible when set app language arabic.

### ISSUE THREAD

**Issue by amitsemwal1** [poovamraj/PinEditTextField#19]
I am using below code to enter 4 digit otp code in my android app.

 ```
 <com.poovam.pinedittextfield.LinePinField
                android:id="@+id/lineField"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="center_horizontal"
                android:layout_marginTop="20dp"
                android:inputType="number"
                android:textColor="@color/colorBlack"
                android:textSelectHandle="@drawable/text_handle"
                android:textSize="25sp"
                app:distanceInBetween="10dp"
                app:highlightColor="@color/colorBlack"
                app:highlightEnabled="true"
                app:highlightSingleFieldMode="true"


                app:isCursorEnabled="true"
                app:lineThickness="2dp"

                app:noOfFields="4" />
```
I have also attach image of both case were in English language fields are shown and and when i am trying to change app language to Arabic the fields are gone , not shown to me.
How can i overcome from this 
![whatsapp image 2019-02-19 at 3 42 41 pm 1](https://user-images.githubusercontent.com/29171672/53007446-48d48180-345d-11e9-87ad-79343d1f3985.jpeg)
![whatsapp image 2019-02-19 at 3 42 41 pm](https://user-images.githubusercontent.com/29171672/53007447-496d1800-345d-11e9-826a-2a17b40cae5e.jpeg)

**Comment by poovamraj** [comment]
Hello, Guess this should be fixed in the lib code. I will try to fix it this weekend and upload. There are also two other issues I have to work on

**Comment by IslamKhSh** [comment]
just add 
        android:layoutDirection="ltr"
to your xml  and it will work ok

**Comment by poovamraj** [comment]
@amitsemwal1 Is it working now? I am closing this issue for now. Please feel free to reopen

**Comment by ahmedhassan1995** [comment]
I confirm that this doesn't fix the problem. the lines are shown in the preview part when setting layout direction to ltr but it doesn't work when running the app

**Comment by Magedsaad** [comment]
i'm still have same issue

**Comment by poovamraj** [comment]
@Magedsaad  did you trying setting this 
android:layoutDirection="ltr"

Can you share the layout XML you are using?

**Comment by Magedsaad** [comment]
yes

**Comment by Magedsaad** [comment]
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:layoutDirection="ltr"
    android:background="@drawable/gradient_bg"
    tools:context=".activiation.ActivationActivity">


    <TextView
        android:id="@+id/textView6"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_marginStart="50dp"
        android:layout_marginLeft="50dp"
        android:layout_marginTop="60dp"
        android:text="رمز التحقيق"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

    <TextView
        android:id="@+id/textView7"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_marginStart="50dp"
        android:layout_marginLeft="50dp"
        android:layout_marginTop="8dp"
        android:text=" يرجى اضافة رمز التحقيق المرسل الى رقم الجوال"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/textView6" />

    <TextView
        android:id="@+id/textView8"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_marginStart="50dp"
        android:layout_marginLeft="50dp"
        android:layout_marginTop="8dp"
        android:text="+966512345678"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/textView7" />


    <com.poovam.pinedittextfield.SquarePinField
        android:id="@+id/squareField"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_marginStart="50dp"
        android:layout_marginTop="8dp"
        android:layout_marginEnd="50dp"
        android:elevation="20dp"
        android:inputType="text"
        android:textSelectHandle="@drawable/text_handle"
        android:textSize="16sp"
        app:cornerRadius="18dp"
        app:fieldBgColor="#fff"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/textView8"
        app:noOfFields="4" />

</androidx.constraintlayout.widget.ConstraintLayout>

**Comment by poovamraj** [comment]
Can you try setting this to the SquarePinField instead?

**Comment by Magedsaad** [comment]
sorry i had to put android:layoutDirection="ltr" in SquarePinField it's done

**Comment by Magedsaad** [comment]
what should i do to integrated with OTP and filled automatically
